### ISSUE TITLE
memoryLeak

### ISSUE THREAD

**Issue by samucati** [bittencourtthulio/TBGPrevisaoTempo#1]
Olá, estou tentando corrigir o exemplo disponibilizado mas não estou encontrando onde está o vazamento de memoria.

![image](https://user-images.githubusercontent.com/11969592/59457161-4623e080-8dee-11e9-978a-be1d3324929f.png)

**Comment by franklingoncalves** [comment]
O vazamento ocorre no datamodule.... o datamodule sobreescreve os count da interface.... tem uma aula do Thulio que ele explica como resolver isso usando o datamodule ou muda o datamodule para uma classe normal.

**Comment by samucati** [comment]
obrigado, vou procurar

**Comment by franklingoncalves** [comment]
Eu mudei o datamodule para uma classe 

unit TBGPrevisaoTempo.Model.ClimaTempo;

interface

uses
  System.SysUtils, System.Classes, IPPeerClient, REST.Client,
  Data.Bind.Components, Data.Bind.ObjectScope, TBGPrevisaoTempo.Model.Entidade,
  TBGPrevisaoTempo.View.Interfaces;

type
  TModelClimaTempo = class(TInterfacedObject, iPrevisaoData)
  private
    FRESTClient1: TRESTClient;
    FRESTRequest1: TRESTRequest;
    FRESTResponse1: TRESTResponse;
    FEntidade : TPrevisaoTempoModel;
    FCodeCity : String;
    FToken : String;
  public
    constructor Create;
    destructor Destroy; override;
    class function New : iPrevisaoData;

    function CodeCity(Value : String) : iPrevisaoData;
    function Token (Value : String) : iPrevisaoData;
    function Entidade(Value : TPrevisaoTempoModel) : iPrevisaoData;
    function FindCityID(City, State : String) : String;
    function ConsultarClima : iPrevisaoData;
  end;

implementation

uses
  System.JSON, System.Types, TBGPrevisaoTempo.Principal, Windows;

{ TModelClimaTempo }

function TModelClimaTempo.CodeCity(Value: String): iPrevisaoData;
begin
  Result := Self;
  FCodeCity := Value;
end;

function TModelClimaTempo.ConsultarClima: iPrevisaoData;
var
  obj, data: TJSONObject;
begin
  Result                   := Self;

  FRESTClient1.BaseURL     := 'http://apiadvisor.climatempo.com.br/api/v1/weather/locale/'+FCodeCity+'/current?token=' + FToken;
  FRESTRequest1.Execute;

  obj                      := FRESTResponse1.JSONValue as TJSONObject;

  data                     := obj.Values['data'] as TJSONObject;
  FEntidade.City           := obj.Values['name'].Value;
  FEntidade.State          := obj.Values['state'].Value;
  FEntidade.Country        := obj.Values['country'].Value;
  FEntidade.Temperature    := StrToIntDef(data.Values['temperature'].Value, 0);
  FEntidade.wind_direction := data.Values['wind_direction'].Value;
  FEntidade.wind_velocity  := data.Values['wind_velocity'].Value.ToDouble;
  FEntidade.humidity       := data.Values['humidity'].Value.ToDouble;
  FEntidade.condition      := data.Values['condition'].Value;
  FEntidade.pressure       := data.Values['pressure'].Value.ToDouble;
  FEntidade.sensation      := data.Values['sensation'].Value.ToInteger;
  FEntidade.date           := data.Values['date'].Value;
//  FEntidade.Seticon('RCL_' + Trim(data.Values['icon'].Value));
end;

constructor TModelClimaTempo.Create;
begin
  inherited;
  FRESTClient1   :=  TRESTClient.Create(nil);
  FRESTRequest1  :=  TRESTRequest.Create(nil);
  FRESTResponse1 :=  TRESTResponse.Create(nil);

  FRESTRequest1.Client  :=  FRESTClient1;
  FRESTRequest1.Response  :=  FRESTResponse1;
end;

destructor TModelClimaTempo.Destroy;
begin
  FreeAndNil(FRESTClient1);
  FreeAndNil(FRESTRequest1);
  FreeAndNil(FRESTResponse1);
  inherited;
end;

function TModelClimaTempo.Entidade(Value: TPrevisaoTempoModel): iPrevisaoData;
begin
  Result    := Self;
  FEntidade := Value;
end;

function TModelClimaTempo.FindCityID(City, State: String): String;
var
  obj : TJSONArray;
  a : TJSONValue;
  data : TJSONObject;
  sd : String;
begin
  FRESTClient1.BaseURL := 'http://apiadvisor.climatempo.com.br/api/v1/locale/city';
  FRESTClient1.AddParameter('name', City);
  FRESTClient1.AddParameter('state', State);
  FRESTClient1.AddParameter('token', FToken);
  FRESTRequest1.Execute;
  sd   := FRESTResponse1.Content;
  obj  := FRESTResponse1.JSONValue as TJSONArray;
  for a in obj do
  begin
    data   := a as TJSONObject;
    Result := data.Values['id'].Value;
  end;
end;

class function TModelClimaTempo.New: iPrevisaoData;
begin
  Result := Self.Create;
end;

function TModelClimaTempo.Token(Value: String): iPrevisaoData;
begin
  Result := Self;
  FToken := Value;
end;

end.

**Comment by samucati** [comment]
fiz conforme você falou, ficou legal, mas continuava com alguns memoryleak na unit TBGPrevisaoTempo.Model.Entidade; se eu usar os icones que voce comentou 
FEntidade.Seticon('RCL_' + Trim(Data.Values['icon'].Value));

removi seu comentario nesse caso e agora traz os icones, e adicionei o destructor abaixo

unit TBGPrevisaoTempo.Model.Entidade; 

destructor TPrevisaoTempoModel.Destroy;
begin
  if Assigned(Ficon) then
  begin
    FreeAndNil(Ficon);
  end;

  inherited;
end;

**Comment by franklingoncalves** [comment]
Oi, nesse link tem a solução para o Memory Leak do datamodule

http://thuliobittencourt.com/blog/gerenciando-memoria-acbr/

**Comment by samucati** [comment]
legal obrigado
